@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### 
GET http://{{host}}/api/calculator
Content-Type: {{contentType}}

### 
GET http://{{host}}/api/calculator/6
Content-Type: {{contentType}}

###
POST http://{{host}}/api/calculator
Content-Type: {{contentType}}

{
    "title":"title 10"
}

### 
PATCH http://{{host}}/api/calculator/63199ad2f701eb237b858d35
Content-Type: {{contentType}}

{
    "title":"title 15"
}

### 
DELETE http://{{host}}/api/calculator/63199ad2f701eb237b858d35
Content-Type: {{contentType}}